video:
  height: 270
  width: 480
  frame_rate: 30
audio:
  rate: 48000
logo:
  paths:
    - "dataset/Brand Images/subway_logo.bmp"
    - "dataset/Brand Images/starbucks_logo.bmp"
    - "dataset2/Brand Images/Mcdonalds_logo.bmp"
    - "dataset2/Brand Images/nfl_logo.bmp"
    - "dataset3/Brand Images/ae_logo.bmp"
    - "dataset3/Brand Images/hrc_logo.bmp"
ad:
  starbucks: "dataset/Ads/Starbucks_Ad_15s"
  subway: "dataset/Ads/Subway_ad_15s"
  mcd: "dataset2/Ads/mcd_Ad_15s"
  nfl: "dataset2/Ads/nfl_Ad_15s"
  ae: "dataset3/Ads/ae_ad_15s"
  hrc: "dataset3/Ads/hrc_ad_15s"
detect:
  debug: false
  export: false
  gamma: 1.6
  saturation: 1.15
  ratio: 0.7
  sift:
    # default: 0
    nfeatures: 0
    # default: 3
    nOctaveLayers: 3
    # default: 0.04
    contrastThreshold: 0.09
    # default: 10
    edgeThreshold: 30
    # default: 1.6
    sigma: 1.6
demo:
  # 0-2
  testcase: 0
