video:
  height: 270
  width: 480
  frame_rate: 30
logo:
  paths:
    - "dataset/Brand Images/subway_logo.bmp"
    - "dataset/Brand Images/starbucks_logo.bmp"
    - "dataset2/Brand Images/Mcdonalds_logo.bmp"
    - "dataset2/Brand Images/nfl_logo.bmp"
    - "dataset3/Brand Images/ae_logo.bmp"
    - "dataset3/Brand Images/hrc_logo.bmp"
detect:
  debug: true
  export: true
  gamma: 1.6
  saturation: 1.15
  ratio: 0.7
  sift:
    # default: 0
    nfeatures: 0
    # default: 3
    nOctaveLayers: 3
    # default: 0.04
    contrastThreshold: 0.09
    # default: 10
    edgeThreshold: 30
    # default: 1.6
    sigma: 1.6
